version: '2'

volumes:
  toster_state:

services:
  toster:
    build: .
    stdin_open: true
    tty: true
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - toster_state:/data:rw
